Metrics/ParameterLists:
  Enabled: false

Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 30

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 15



Style/GlobalVars:
  Enabled: false